# This is a basic workflow to help you get started with Actions

name: sync

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule:
    - cron: '30 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || github.event.sender.login == 'uuz'

    steps:
      - uses: actions/checkout@v2

      - name: sync github/lxk0301
        uses: fo7/sync-repo@main
        with:
          src: github/lxk0301
          dst: github/18u
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "jd_scripts"
          account_type: org
          name_changed: true
          # clone_style: https

      - name: sync github/Zero-S1
        uses: fo7/sync-repo@main
        with:
          src: github/Zero-S1
          dst: github/18u
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "xmly_speed,JD_tools"
          account_type: org
          name_changed: true

      - name: sync github/sazs34
        uses: fo7/sync-repo@main
        with:
          src: github/sazs34
          dst: github/18u
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "MyActions,TaskConfig,Convert"
          account_type: org
          name_changed: true

      - name: sync github/NobyDa
        uses: fo7/sync-repo@main
        with:
          src: github/NobyDa
          dst: github/18u
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "Script"
          account_type: org
          name_changed: true

      - name: sync github/Sunert
        uses: fo7/sync-repo@main
        with:
          src: github/Sunert
          dst: github/18u
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "Scripts"
          account_type: org
          name_changed: true

      - name: sync github/chavyleung
        uses: fo7/sync-repo@main
        with:
          src: github/chavyleung
          dst: github/18u
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "scripts"
          account_type: org
          name_changed: true

      - name: sync github/Tartarus2014
        uses: fo7/sync-repo@main
        with:
          src: github/Tartarus2014
          dst: github/18u
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "For-own-use,Loon-Script,Surge-Script,Shadowrocket-Script,QuantumultX-Script"
          account_type: org
          name_changed: true

      - name: sync github/mengshouer
        uses: fo7/sync-repo@main
        with:
          src: github/mengshouer
          dst: github/18u
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "CheckinBox"
          account_type: org
          name_changed: true

      - name: sync github/BlueskyClouds
        uses: fo7/sync-repo@main
        with:
          src: github/BlueskyClouds
          dst: github/18u
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "My-Actions"
          account_type: org
          name_changed: true

      - name: sync github/zZPiglet
        uses: fo7/sync-repo@main
        with:
          src: github/zZPiglet
          dst: github/18u
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          static_list: "Task"
          account_type: org
          name_changed: true

