# This is a basic workflow to help you get started with Actions

name: sync

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule:
    - cron: '30 */2 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: sync lxk0301/jd_scripts
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/lxk0301
          dst: github/18u
          dst_key: ${{ secrets.UUZ_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.UUZ_GITHUB_TOKEN }}
          white_list: "jd_scripts"
          account_type: org
